# Welcome to Numpy Tutorial

In [2]:
import numpy as np

In [3]:
myarr=np.array([3,1,45],np.int64)

In [4]:
myarr[0]

3

In [5]:
myarr.shape

(3,)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr

array([ 3,  1, 45])

# Array Creation: conversion from other python structures

In [8]:
listarray=np.array([[1,2,3],[5,6,3]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 6, 3]])

In [10]:
listarray.dtype

dtype('int64')

In [11]:
listarray.shape

(2, 3)

In [12]:
listarray.size

6

In [13]:
zeros=np.zeros((2,5))

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
range=np.arange(15)

In [16]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace=np.linspace(1,50,6)

In [18]:
lspace

array([ 1. , 10.8, 20.6, 30.4, 40.2, 50. ])

In [19]:
emp=np.empty((3,3))

In [20]:
emp

array([[4.64222906e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [21]:
emp_like=np.empty_like(lspace)

In [22]:
emp_like

array([ 1. , 10.8, 20.6, 30.4, 40.2, 50. ])

In [23]:
ide=np.identity(10)

In [24]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
ide.shape

(10, 10)

In [26]:
ide.reshape(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
arr=np.arange(20)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
arr.shape

(20,)

In [32]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [33]:
arr=np.array(x)

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [35]:
arr.sum(axis=0)

array([12,  8,  9])

In [36]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [37]:
a=arr.T

In [38]:
a.sum(axis=0)

array([ 6, 15,  8])

In [39]:
for item in a.flat:
    print(item)

1
4
7
2
5
1
3
6
0


In [40]:
arr.ndim

2

In [41]:
a.ndim

2

In [42]:
arr.size

9

In [43]:
a.size

9

In [44]:
a.shape

(3, 3)

In [45]:
arr.nbytes

72

In [46]:
a.nbytes

72

In [47]:
one=np.array([1,3,4,65,6])

In [48]:
one

array([ 1,  3,  4, 65,  6])

In [49]:
one.argmax()

3

In [50]:
one.argmin()

0

In [51]:
one.sort()

In [52]:
one

array([ 1,  3,  4,  6, 65])

In [53]:
one.argsort()

array([0, 1, 2, 3, 4])

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
arr.argmin()

8

In [56]:
arr.argmax()

6

In [57]:
arr.argmax(axis=0)

array([2, 1, 1])

In [58]:
arr.argmin(axis=0)

array([0, 2, 2])

In [59]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [60]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [61]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [62]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [63]:
arr1=np.array([[2, 7, 3],
       [4, 3, 6],
       [7, 6, 0]])

In [64]:
arr+arr1

array([[ 3,  9,  6],
       [ 8,  8, 12],
       [14,  7,  0]])

In [65]:
arr*arr1

array([[ 2, 14,  9],
       [16, 15, 36],
       [49,  6,  0]])

In [66]:
square=np.sqrt(arr)

In [67]:
square

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [68]:
s=arr.sum()

In [69]:
s

29

In [70]:
s.max()

29

In [71]:
arr.max()

7

In [72]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [73]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
np.count_nonzero(arr)

8

In [75]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [76]:
arr[0,2]=0

In [77]:
np.nonzero(arr)

(array([0, 0, 1, 1, 1, 2, 2]), array([0, 1, 0, 1, 2, 0, 1]))

In [78]:
py_arr=[2,5,4,8]

In [79]:
np_arr=np.array(arr)

In [80]:
import sys

In [81]:
py_arr=[2,5,4,8]

In [82]:
np_arr=np.array(py_arr)

In [83]:
sys.getsizeof(1)*len(py_arr)

112

In [84]:
np_arr.itemsize*np_arr.size

32

In [85]:
np_arr.tolist()

[2, 5, 4, 8]